export const Authority = {
  Home: "A000",
  TurnOffAlarm: "A001",
  ProductManagment: "U000",
  IOTDeviceManagment: "U001",
  IOTDeviceManagment_Insert: "UP01",
  IOTDeviceManagment_Edit: "UP02",
  NonIOTDeviceManagment: "U002",
  NonIOTDeviceManagment_Insert: "UN01",
  NonIOTDeviceManagment_Edit: "UN02",
  IOTDeviceModelManagment: "U003",
  IOTDeviceModelManagment_Insert: "UM01",
  IOTDeviceModelManagment_Edit: "UM02",
  DeviceLog: "C000",
  ServiceLog: "S000",
  ServiceLog_Insert: "S001",
  ServiceLog_Edit: "S002",
  ServiceLog_Export: "S003",
  ServiceLog_Detail: "S004",
  WorkSchedule: "BC00",
  WorkSchedule_Insert: "BC01",
  WorkSchedule_Edit: "BC02",
  WorkSchedule_Detail: "BC03",
  AuthorityManagment: "Y000",
  AuthorityManagment_Insert: "Y001",
  AuthorityManagment_Edit: "Y002",
  LocationManagment: "M000",
  LocationManagment_Insert: "M001",
  LocationManagment_Edit: "M002",
  SystemManagment: "SM00",
  UserManagment: "SM01",
  UserManagment_Insert: "SMK1",
  UserManagment_Edit: "SMK2",
  RoleManagement: "SM02",
  RoleManagement_Insert: "SMR1",
  RoleManagement_Edit: "SMR2",
  IOTDisplayDeviceManagment:"U004",
  IOTDisplayDeviceManagment_Insert:"US01",
  IOTDisplayDeviceManagment_Edit:"US02"
};
